repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=512']
      - id: trailing-whitespace
        exclude: __snapshots__/
      - id: debug-statements
      - id: fix-byte-order-marker
        exclude: __snapshots__/
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-crlf
        exclude: __snapshots__/
      - id: remove-tabs
        exclude: __snapshots__/
