command_timeout = 1000
add_newline = true
palette = "gruvbox"

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$rust\
$docker_context\
$aws\
$jobs\
$cmd_duration\
$line_break\
$character"""

[palettes.gruvbox]
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
purple = "#d3869b"
orange = "#fe8019"
aqua = "#8ec07c"
fg = "#ebdbb2"
bg = "#282828"
gray = "#928374"
dark_red = "#cc241d"
dark_green = "#98971a"
dark_blue = "#458588"

[fill]
symbol = " "

[directory]
style = "bold blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = " "
"~" = " "

[git_branch]
symbol = ""
style = "green"
format = "[$symbol $branch(:$remote_branch) ]($style)"

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = ""
style = "blue"
format = "[$symbol $version ]($style)"

[lua]
symbol = ""
style = "blue"
format = "[$symbol $version ]($style)"

[nodejs]
symbol = ""
style = "green"
format = "[$symbol $version ]($style)"

[golang]
symbol = ""
style = "aqua"
format = "[$symbol $version ]($style)"

[rust]
symbol = ""
style = "orange"
format = "[$symbol $version ]($style)"

[docker_context]
symbol = ""
style = "purple"
format = "[$symbol $context ]($style)"

[aws]
symbol = ""
style = "orange"
format = '[$symbol ($profile )(($region) )]($style)'

[jobs]
symbol = "✦"
style = "blue"
format = "[$symbol$number ]($style)"

[cmd_duration]
min_time = 2_000
style = "gray"
format = "[󰔟 $duration ]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
